Green-Software-Foundation/awesome-green-software

readme.md

Added web tool - greenframe.io and article on google cloud (how to incorporate carbon free region)

Added Web Tool and Article

---

readme.md

Can be merged in after #47 to avoid conflicts

Added an article talking about sustainability as a first-class citizen for AI systems

---

readme.md

I came across this tool this week - a specific service for managing compute energy consumption at the datacentre level for on-prem folks.

Add an interesting new service for datacentre energy management

---

readme.md

Submit PR to dev branch (original #79) (updated)

Update to include Kepler tool

---

readme.md

http://ec0lint.com/ An interesting tool providing suggestions for minimising carbon footprint of websites.

Add ec0lint to Web tools.

---

readme.md

Add kube-green

---

readme.md

Added an analysis paper on the carbon saving potential of temporal workload shifting in cloud computing from Middleware conference 2021

Added paper on carbon saving potentials in the cloud

---

readme.md

Added Globemallow.io to Web Category.

globemallowAdd

---

readme.md

Two updates, one minor:
* Added Carbon Aware SDK now that it has gone to v1.0 :) 🎉
* Fixed the title casing on the title 'code based' to be 'Code based'

Added Carbon Aware SDK and minor typo fix

---

readme.md

update joular repository links

---

readme.md

* Added Hardware Sentry in General/Energy
* Moved CO2Scope from AI/Energy to General/Energy
* Added ecoIndex.fr to OS based/Web
* Updated ToC

Hardware Sentry, ecoIndex and ToC update

---

readme.md

Just a few minor syntax fixes in Markdown syntax (notably empty lines after headings)

Various markdown fixes

---

readme.md

This updates adds 2 PowerShell modules for retrieving carbon emissions for power grid using free accounts

Added PSElectricityMaps and PSWattTime

---

readme.md

@dtoakley recloned against dev and resolved the conflicts

Fixing dead link in readme.

---

readme.md

Carbon AppInsights is an Azure Functions PowerShell based solution with deployment code in Bicep for getting emissions data for Azure regions from Electricity Maps and logging that data to Application Insights / Azure Monitor

Added Carbon AppInsights

---

readme.md

Hello, 
just adding a new entry to the README.

Add CAST Highlight to awesome green software list

---

readme.md

EnergiBridge: Empowering Software Sustainability through Cross-Platform Energy Measurement

Added paper on cross-platform energy measurement

---

readme.md

Adds a new category of macOS and also adds a link to the power hog resource monitoring software

Adds power hog

---

readme.md

Update readme.md - New link for joularjx library

---

readme.md

Hi!
I thought it would be of interest to link to a multi-cloud SaaS solution I'm working on for monitoring cloud emissions.
I'm a new to the community, so I hope I've done the PR and commits correctly 😃

Added link to Gaia Gen

---

readme.md

Added a tool, some relevant publications, a course, and a book. 
Created a new category in Research for Methodologies.
Signed-off-by: Ivano Malavolta (i.malavolta@vu.nl)

Update readme.md including additional material

---

readme.md

We have identified 22 green coding practices or energy patterns for web applications. We verified these patterns with software developers to see if they could identify them in their codebase.  We also brought evidence for two of these practices. We measured two patterns to see if they consumed more energy than their counterpart.

Add research related to web development

---

readme.md

This PR adds new resources and an article to the awesome-green-software directory, focusing on carbon offsetting and integrating environmental actions into software.
- **AI Carbon section:** Added a resource for offsetting the carbon from AI workloads.
- **Code-based section:** Added a resource for an API to integrate environmental actions.
- **Articles section:** Added a link to the article "Complete Guide to Carbon Offsetting: APIs and Shopify App".
These updates provide developers with more options for measuring, reducing, and offsetting carbon emissions in their projects.

Add resources for carbon offsetting and sustainability
